# Use the official Python image from Docker Hub
FROM python:3.11-slim

# set all the environment and install all the dependencies here 

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Command to run the application
CMD ["python", "app.py"]